### ISSUE TITLE
#US04 #TK11 Agregar un botón de recuperación de contraseña y que envíe dicha contraseña al correo electrónico de registro

### ISSUE THREAD

**Issue by DHerrera85** [OneDrop-ISPC-PP/APP-OneDrop#11]
#TK07 Agregar un botón de recuperación de contraseña y que envíe dicha contraseña al correo electrónico de registro

**Comment by DHerrera85** [comment]
To do

**Comment by DavidCosta92** [comment]
En la App mobile esta funcionalidad ya esta implementada, queda finalizar funcion en web

**Comment by DHerrera85** [comment]
Completado!
