### ISSUE TITLE
#US02 Como usuario del sitio OneDrop quiero que una vez que realice el registro en la página, que mis datos queden guardados para una próxima entrada para no tener que registrarme nuevamente

### ISSUE THREAD

**Issue by martin-delhugo** [OneDrop-ISPC-PP/APP-OneDrop#13]
Como usuario del sitio OneDrop quiero que una vez que realice el registro en la página, que mis datos queden guardados para una próxima entrada para no tener que registrarme nuevamente

**Comment by DavidCosta92** [comment]
En el ultimo commit, este issue queda solucionado!
