### ISSUE TITLE
#US02 #TK06 Conectar efectivamente la Base de Datos al Backend

### ISSUE THREAD

**Issue by martin-delhugo** [OneDrop-ISPC-PP/APP-OneDrop#14]
Conectar efectivamente la Base de Datos al Backend

**Comment by DavidCosta92** [comment]
La conexion back - angular esta en progreso.. @martin-delhugo subira pronto el fix final, en cuanto a android, creare un nuevo issue para separar tareas y evitar ambiguedad

**Comment by DHerrera85** [comment]
Debido a la complejidad de la tarea, se pasa para el Sprint 2

**Comment by DavidCosta92** [comment]
Esta tarea esta terminada!
