### ISSUE TITLE
#US04 Como usuario de la app OneDrop quiero loguearme de manera exitosa y poder recuperar la contraseña en caso de olvidarla para poder utilizar todas las funciones

### ISSUE THREAD

**Issue by DHerrera85** [OneDrop-ISPC-PP/APP-OneDrop#2]
#US03 Como usuario de la app OneDrop quiero loguearme de manera exitosa y poder recuperar la contraseña en caso de olvidarla para poder utilizar todas las funciones

**Comment by DHerrera85** [comment]
Para hacer

**Comment by DavidCosta92** [comment]
Finalizado!
