### ISSUE TITLE
#US12 #TK26 Eliminar dependencias innecesarias de almacenamiento SQLite, y logica asociada

### ISSUE THREAD

**Issue by DavidCosta92** [OneDrop-ISPC-PP/APP-OneDrop#21]

**Comment by DavidCosta92** [comment]
Al migrar el almacenamiento al servidor, dejara de ser necesario el almacenamiento en dispositivo, por tanto, toda la logica asociada debera ser eliminada y migrada al server

**Comment by martin-delhugo** [comment]
Se agregaron carpetas y archivos correspondientes a las dependencias y al cache en el gitignore. Pero todavía faltan borrar dependencias viejas.

**Comment by DavidCosta92** [comment]
Se limpiaron las dependencias inecesarias, por lo que se da por finalizado
