### ISSUE TITLE
#US12 #TK28 Verificar conexion correcta desde distintos dispositivos personales

### ISSUE THREAD

**Issue by DavidCosta92** [OneDrop-ISPC-PP/APP-OneDrop#23]
**Una vez terminada #US12 #TK27**, realizar testing de integracion desde dispositivos personales para asegurar una correcta implementacion de la migracion

**Comment by DavidCosta92** [comment]
Esta tarea esta lista en terminos de codificacion, queda ser testeada de manera end to end

**Comment by danielasgomez273** [comment]
Cerrada :hourglass:
