### ISSUE TITLE
#US00 #TK02 Documentar en la Wiki del Proyecto y el Documento IEEE 830.

### ISSUE THREAD

**Issue by hechizera10** [OneDrop-ISPC-PP/APP-OneDrop#33]

**Comment by hechizera10** [comment]
# ENLACES A RESPECTIVOS DOCUMENTOS

[WIKI DEL PROYECTO ](https://github.com/OneDrop-ISPC-PP/APP-OneDrop/wiki)
[DOCUMENTO IEEE 830](https://docs.google.com/document/d/1osBcaCYlugKHNrzTfUBZit3BKx4n_ulV/edit?usp=sharing&ouid=107263608878982584692&rtpof=true&sd=true)

**Comment by danielasgomez273** [comment]
Chicos! En [éste link](https://www.figma.com/file/nRXLY6bOIZlvhSqIacjufT/OneDrop---SiteMap-2024-(Copy)?type=whiteboard&node-id=1-1281&t=BFbpOEvsToVBQU50-0) el mapa del sitio en Figma. Traje acá los de años anteriores y armé el nuevo. Subo a la carpeta de Drive el SiteMap en formato PNG. Lo agregamos en Anexos en el IEEE830? O lo dejamos sólo en la Wiki?

**Comment by DHerrera85** [comment]
Esta US se encuentra en proceso, se cerrará una vez concluido el Sprint 2

**Comment by DHerrera85** [comment]
Completado
