### ISSUE TITLE
#US10 Como usuario del sitio web OneDrop quiero poder elegir entre al menos 5 servicios disponibles para su eventual contratación

### ISSUE THREAD

**Issue by DHerrera85** [OneDrop-ISPC-PP/APP-OneDrop#39]
#US10 Como usuario del sitio web OneDrop quiero poder elegir entre al menos 5 servicios disponibles para su eventual contratación

**Comment by danielasgomez273** [comment]
Faltan minimo de 5 servicios. Definir los servicios a agregar

**Comment by DHerrera85** [comment]
Completado
