### ISSUE TITLE
#US13 Como usuario/administrador del sitio One Drop quiero que el dashboard (panel de control) tenga información sincronizada y dinámica con posibilidad de manipularla para una mejor experiencia

### ISSUE THREAD

**Issue by martin-delhugo** [OneDrop-ISPC-PP/APP-OneDrop#42]
Como usuario/administrador del sitio One Drop quiero que el dashboard (panel de control) tenga información sincronizada y dinámica con posibilidad de manipularla para una mejor experiencia.

**Comment by maxicovaro** [comment]
Finalizada
