### ISSUE TITLE
#US03 #TK08 Controlar el BackEnd y detectar el error de cierre de aplicación

### ISSUE THREAD

**Issue by jimepar** [OneDrop-ISPC-PP/APP-OneDrop#6]

**Comment by DavidCosta92** [comment]
Buenas, necesitariamos mas contexto sobre el bug!  En que accion se produce el cierre? Algun mensaje de error que se genere?

**Comment by DavidCosta92** [comment]
Bug solucionado, el error estaba en la aplicacion android y no en el backend, por tanto procedo a cerrar el issue
